chat-prefix: '&6[&eBee Box&6] &7> '

welcome-player:
  - '&6Welcome to Bee Box MC!'
  - '&eOur server uses a greylist, you can''t interact with the world until you become a member.'
  - '&eUse /apply to get started!'

welcome-global: '&a%player% has joined Bee Box MC for the first time!'

greet-new: '&6Welcome, &e%player%&6!'
new-sound:
  sound: entity.player.levelup
  volume: 1.5
  pitch: 0.69

greet-returning: '&6Welcome back, &e%player%&6!'
returning-sound:
  sound: block.beehive.enter
  volume: 1.5
  pitch: 1.0

accepted-player: '&6Congratulations! &eYou''re accepted as a member - use /rules, /information, and /map to learn more about Bee Box MC!'
accepted-global: '&a%player% was accepted as a member!'

help:
  - '<dark_grey><bold>-------- << - <yellow>[ <white>Bee Box Help</white> ] <dark_grey>- >> --------'
  - '&6/apply: &fApply to become a member'
  - '&6/co inspect: &fToggle the block inspector &7&o(Donor only)'
  - '&6/cosmetic: &fChange your active cosmetics &7&o(Donor only)'
  - '&6/discord: &fJoin our discord'
  - '&6/discord link: &fLink your Minecraft and Discord accounts'
  - '&6/info: &fView useful information'
  - '&6/map: &fView the online map'
  - '&6/portal: &fGet coordinates to build linking portals'
  - '&6/rules: &fRead the server''s rules'
  - '&6/shop: &fVisit the store'
  - '&6/slime: &fCheck if a chunk spawns slimes &7&o(Donor only)'
  - '&8&l----------------------------------------'

info:
  - '&8&l---------- &e&l[ &f&lSeason Info &e&l] &8&l----------'
  - '&6Soft Border: &f15000x15000'
  - '&7&oBuild your home within this area!'
  - ''
  - '&6Hard Border: &f20000x20000'
  - '&7&oHarvest resources beyond the soft border.'
  - '&7&oAreas beyond the soft border may reset!'
  - ''
  - '&6Notable Locations:'
  - '&e→ Spawn &f(0,0)'
  - '&e→ Nether Hub &f(?,?)'
  - '&e→ Shopping District &f(?,?)'
  - '&8&l------------------------------------'

map: '&bClick me &fto view the online map!'
map-link: https://map.beeboxmc.com
map-hover: '&7&oRedirects to https://map.beeboxmc.com'

rules:
  - '&8&l---------- &e&l[ &f&lBee Box Rules &e&l] &8&l----------'
  - '&e→ &6Build at least 100 blocks away from spawn'
  - '&e→ &6Only take what belongs to you'
  - '&e→ &6Respect space — build away from others'
  - '&e→ &6Only engage in PvP with mutual consent'
  - ''
  - '&e&oIf you see any malicious behavior please alert staff!'
  - '&e&oStaff are denoted by &fMods&1*&e&o, &fAdmins&6*&e&o, and &fDevs&5*&e&o.'
  - '&8&l------------------------------------'

# Max Average Time Between Chats
chat_spam_threshold: 0.75

# Max Time Between Chats Before Time Array is Reset
chat_time_expiry: 3

# Amount of Time to Mute Player
mute_time: 3

# Max Messages Before Mute
max_messages: 3

enabled-commands:
  accept: true
  apply: true
  heal: true
  help: true
  info: true
  map: true
  portal: true
  rules: true
  slime: true
  unaccept: true