chat-prefix: '&6[&eBee Box&6] &7> '

welcome-player:
  - '&6Welcome to Bee Box MC!'
  - '&eOur server uses a greylist, you can''t interact with the world until you become a member.'
  - '&eUse /apply to get started!'

welcome-global: '&a%player% has joined Bee Box MC for the first time!'

greet-new: '&6Welcome, &e%player%&6!'
new-sound:
  sound: entity.player.levelup
  volume: 1.5
  pitch: 0.69

greet-returning: '&6Welcome back, &e%player%&6!'
returning-sound:
  sound: block.beehive.enter
  volume: 1.5
  pitch: 1.0

apply-form: 'https://forms.gle/8L98ueJkJ6Znscb19'
accepted-player: '&6Congratulations! &eYou''re accepted as a member - use /rules, /information, and /map to learn more about Bee Box MC!'
accepted-global: '&a%player% was accepted as a member!'

help:
  - '<dark_grey><bold>-------- << - <yellow>[ <white>Bee Box Help</white> ] <dark_grey>- >> --------'
  - '&6/apply: &fApply to become a member'
  - '&6/co inspect: &fToggle the block inspector &7&o(Donor only)'
  - '&6/cosmetic: &fChange your active cosmetics &7&o(Donor only)'
  - '&6/discord: &fJoin our discord'
  - '&6/discord link: &fLink your Minecraft and Discord accounts'
  - '&6/info: &fView useful information'
  - '&6/map: &fView the online map'
  - '&6/portal: &fGet coordinates to build linking portals'
  - '&6/rules: &fRead the server''s rules'
  - '&6/shop: &fVisit the store'
  - '&6/slime: &fCheck if a chunk spawns slimes &7&o(Donor only)'
  - '&8&l----------------------------------------'

info:
  - '&8&l---------- &e&l[ &f&lSeason Info &e&l] &8&l----------'
  - '&6Soft Border: &f15000x15000'
  - '&7&oBuild your home within this area!'
  - ''
  - '&6Hard Border: &f20000x20000'
  - '&7&oHarvest resources beyond the soft border.'
  - '&7&oAreas beyond the soft border may reset!'
  - ''
  - '&6Notable Locations:'
  - '&e→ Spawn &f(0,0)'
  - '&e→ Nether Hub &f(?,?)'
  - '&e→ Shopping District &f(?,?)'
  - '&8&l------------------------------------'

map: '&bClick me &fto view the online map!'
map-link: https://map.beeboxmc.com

rules:
  - '&8&l---------- &e&l[ &f&lBee Box Rules &e&l] &8&l----------'
  - '&e→ &6Build at least 100 blocks away from spawn'
  - '&e→ &6Only take what belongs to you'
  - '&e→ &6Respect space — build away from others'
  - '&e→ &6Only engage in PvP with mutual consent'
  - ''
  - '&e&oIf you see any malicious behavior please alert staff!'
  - '&e&oStaff are denoted by &fMods&1*&e&o, &fAdmins&6*&e&o, and &fDevs&5*&e&o.'
  - '&8&l------------------------------------'

# Max Average Time Between Chats
chat_spam_threshold: 0.75

# Max Time Between Chats Before Time Array is Reset
chat_time_expiry: 3

# Amount of Time to Mute Player
mute_time: 3

# Max Messages Before Mute
max_messages: 3

# AFK threshold (in seconds), defaults to 10 minutes (600 seconds)
afk: 600

enabled-commands:
  accept: true
  apply: true
  broadcast: true
  heal: true
  help: true
  info: true
  map: true
  portal: true
  rules: true
  slime: true
  smite: false
  unaccept: true

# Armor Stand poses for Donors and above
armor:
  standPose:
    1:
      arms: false
      bodyPose: [0, 0, 0]
      headPose: [0, 0, 0]
      leftLegPose: [0, 0, 0]
      rightLegPose: [0, 0, 0]
    2:
      bodyPose: [ 0, 0, 0 ]
      headPose: [ 0, 0, 0 ]
      leftLegPose: [ 0, 0, 0 ]
      rightLegPose: [ 0, 0, 0 ]
      leftArmPose: [ 339, 0, 346 ]
      rightArmPose: [ 339, 0, 15 ]
    3:
      bodyPose: [ 0, 0, 0 ]
      headPose: [ 0, 0, 0 ]
      leftLegPose: [ 0, 0, 0 ]
      rightLegPose: [ 0, 0, 0 ]
      leftArmPose: [ 0, 0, 0 ]
      rightArmPose: [ 0, 0, 0 ]
    4:
      bodyPose: [ 0, 0, 0 ]
      headPose: [ 14, 0, 0 ]
      leftLegPose: [ 0, 0, 0 ]
      rightLegPose: [ 0, 0, 0 ]
      leftArmPose: [ 312, 0, 39 ]
      rightArmPose: [ 312, 0, 323 ]
    5:
      bodyPose: [ 0, 0, 0 ]
      headPose: [ 356, 0, 0 ]
      leftLegPose: [ 0, 0, 0 ]
      rightLegPose: [ 0, 0, 0 ]
      leftArmPose: [ 0, 0, 343 ]
      rightArmPose: [ 282, 0, 0 ]
    6:
      bodyPose: [ 0, 0, 0 ]
      headPose: [ 346, 0, 0 ]
      leftLegPose: [ 11, 0, 353 ]
      rightLegPose: [ 0, 0, 8 ]
      leftArmPose: [ 31, 0, 353 ]
      rightArmPose: [ 248, 37, 0 ]
    7:
      bodyPose: [ 0, 0, 0 ]
      headPose: [ 346, 0, 0 ]
      leftLegPose: [ 11, 0, 353 ]
      rightLegPose: [ 0, 0, 8 ]
      leftArmPose: [ 254, 37, 0 ]
      rightArmPose: [ 254, 324, 0 ]
    8:
      bodyPose: [ 0, 0, 0 ]
      headPose: [ 346, 0, 0 ]
      leftLegPose: [ 11, 0, 353 ]
      rightLegPose: [ 0, 0, 8 ]
      leftArmPose: [ 254, 341, 0 ]
      rightArmPose: [ 241, 40, 0 ]
    9:
      bodyPose: [ 0, 0, 0 ]
      headPose: [ 0, 0, 0 ]
      leftLegPose: [ 0, 0, 0 ]
      rightLegPose: [ 0, 0, 0 ]
      leftArmPose: [ 0, 0, 346 ]
      rightArmPose: [ 309, 338, 15 ]
    10:
      bodyPose: [ 0, 6, 0 ]
      headPose: [ 356, 47, 0 ]
      leftLegPose: [ 0, 40, 350 ]
      rightLegPose: [ 0, 304, 0 ]
      leftArmPose: [ 18, 0, 353 ]
      rightArmPose: [ 248, 47, 0 ]
    11:
      bodyPose: [ 0, 0, 0 ]
      headPose: [ 14, 23, 0 ]
      leftLegPose: [ 18, 141, 350 ]
      rightLegPose: [ 349, 108, 0 ]
      leftArmPose: [ 0, 0, 225 ]
      rightArmPose: [ 265, 334, 0 ]
    12:
      bodyPose: [ 0, 0, 0 ]
      headPose: [ 346, 348, 0 ]
      leftLegPose: [ 0, 0, 353 ]
      rightLegPose: [ 315, 0, 0 ]
      leftArmPose: [ 268, 13, 225 ]
      rightArmPose: [ 268, 348, 0 ]
    13:
      bodyPose: [ 0, 355, 0 ]
      headPose: [ 356, 30, 0 ]
      leftLegPose: [ 238, 0, 306 ]
      rightLegPose: [ 349, 33, 343 ]
      leftArmPose: [ 0, 0, 242 ]
      rightArmPose: [ 0, 0, 120 ]
    14:
      bodyPose: [ 0, 351, 0 ]
      headPose: [ 356, 324, 0 ]
      leftLegPose: [ 346, 0, 12 ]
      rightLegPose: [ 248, 324, 343 ]
      leftArmPose: [ 0, 0, 242 ]
      rightArmPose: [ 0, 0, 120 ]