# Help Command Output
help:
  - '<dark_grey><bold>-------- << - <yellow>[ <white>Bee Box Help</white> ] <dark_grey>- >> --------'
  - '&6/apply: &fApply to become a member'
  - '&6/co inspect: &fToggle the block inspector &7&o(Donor only)'
  - '&6/cosmetic: &fChange your active cosmetics &7&o(Donor only)'
  - '&6/discord: &fJoin our discord'
  - '&6/discord link: &fLink your Minecraft and Discord Accounts'
  - '&6/info: &fView general information'
  - '&6/map: &fView the online map'
  - '&6/portal: &fProvides coordinates to build a linkable portal'
  - '&6/rules: &fRead the server''s rules'
  - '&6/shop: &fView the store'
  - '&6/slime: &fChecks if a chunk spawns slimes &7&0(Donor only)'
  - '&8&l----------------------------------------'

# Info Command Output
info:
  - '&8&l---------- &e&l[ &f&lSeason 1 Info &e&l] &8&l----------'
  - '&6Soft Border: &f10000x10000'
  - '&7&oBuild your home within this area!'
  - ''
  - '&6Hard Border: &f15000x15000'
  - '&7&oHarvest resources beyond the soft border!'
  - '&7&oAreas beyond the soft border may reset'
  - ''
  - '&6Notable Locations:'
  - '&e→ Spawn &f(0,0)'
  - '&e→ Nether Hub Portal &f(?,?)'
  - '&e→ Shopping District &f(?,?)'
  - '&8&l------------------------------------'

# Map Command Output
map: '&6[&eBee Box&6] &e> &fClick me to view the online map!'

# Map URL
map-link: https://map.beeboxmc.com

# Map Hover Event
map-hover: '&7&oRedirects to https://map.beeboxmc.com'

# Rules Command Output
rules:
  - '&8&l---------- &e&l[ &f&lBee Box Rules &e&l] &8&l----------'
  - '&e→ &6Don''t build within 100 blocks of spawn &7&o(without permission)'
  - '&e→ &6Don''t take items that aren''t yours'
  - '&e→ &6Don''t build in other people''s bases'
  - '&e→ &6Don''t PvP &7&o(unless both parties consent)'
  - ''
  - '&e&oIf you see any malicious behavior please alert a staff member'
  - '&8&l------------------------------------'

# Max Average Time Between Chats
chat_spam_threshold: 0.75

# Max Time Between Chats Before Time Array is Reset
chat_time_expiry: 3

# Amount of Time to Mute Player
mute_time: 3

# Max Messages Before Mute
max_messages: 3