name: SurvivalUtilities
version: '${project.version}'
main: survival.utilities.survivalutilities.SurvivalUtilities
depend: [TAB]
api-version: 1.19
authors: [ wmn ]
description: Custom additions for survival server
commands:
  accept:
    description: Accept/unaccept players as members
    usage: /accept <player>, /unaccept <player>
    permission: survivalutil.accept
    aliases: [unaccept]
  apply:
    description: Apply to join as a member
    usage: /apply
    permission: survivalutil.apply
  broadcast:
    description: Broadcasts a message to the server
    usage: /broadcast <message>
    permission: survivalutil.broadcast
  heal:
    description: Restore health and hunger of a player
    usage: /heal <player>
    permission: survivalutil.heal
  help:
    description: Displays help menu
    usage: /help
    aliases: [assist, assistance, aid, aids, support, supports, guide, guidance]
  info:
    description: Display map info
    usage: /info
    aliases: [information, detail, details, find, finds, finding, item, items]
  map:
    description: Displays map link
    usage: /map
    aliases: [maps, world, worlds, view, views, link, links, overview, webmap, webmaps, dynmap, dynmaps]
  portal:
    description: Provides coordinates to build a linkable Nether Portal
    usage: /portal
    aliases: [nether, overworld]
  reload:
    description: Reload configs
    usage: /survivalutilities:reload
    permission: survivalutil.reload
  rules:
    description: Displays the rules of the server
    usage: /rules
    aliases: [rule]