name: SurvivalUtilities
version: '${project.version}'
main: survival.utilities.survivalutilities.SurvivalUtilities
api-version: 1.19
authors: [ wmn ]
description: Custom additions for survival server
commands:
  apply:
    description: Apply to join as a member
    usage: /apply
    permission: survivalutil.apply
  accept:
      description: Accept as a member
      usage: /accept <player>
      permission: survivalutil.accept
  unaccept:
      description: Undo accept of a member
      usage: /unaccept <player>
      permission: survivalutil.unaccept