name: SurvivalUtilities
version: '${project.version}'
main: me.wesleynichols.survivalutilities.SurvivalUtilities
depend: [TAB]
api-version: 1.19
authors: [ wmn ]
description: Lightweight utilities for server members
commands:
  accept:
    description: Accept/unaccept players as members
    usage: /accept <player>
    permission: survivalutil.accept
  apply:
    description: Apply to join as a member
    usage: /apply
    permission: survivalutil.apply
  broadcast:
    description: Broadcasts a message to the server
    usage: /broadcast <message>
    permission: survivalutil.broadcast
  heal:
    description: Restore health and hunger of a player
    usage: /heal <player>
    permission: survivalutil.heal
  help:
    description: Displays help menu
    usage: /help
  info:
    description: Display map info
    usage: /info
    aliases: [information]
  map:
    description: Displays map link
    usage: /map
    aliases: [dynmap]
  portal:
    description: Provides coordinates to build a linkable Nether Portal
    usage: /portal
  reload:
    usage: /survivalutilities:reload
    permission: survivalutil.reload
  rules:
    description: Displays server rules
    usage: /rules
  slime:
    description: Checks whether the current chunk is a slime chunk
    usage: /slime
    permission: survivalutil.slime
  unaccept:
    description: Accept/unaccept players as members
    usage: /unaccept <player>
    permission: survivalutil.unaccept