name: SurvivalUtilities
version: '${project.version}'
main: survival.utilities.survivalutilities.SurvivalUtilities
depend: [TAB]
api-version: 1.19
authors: [ wmn ]
description: Custom additions for survival server
commands:
  accept:
    description: Accept as a member
    usage: /accept <player>
    permission: survivalutil.accept
  apply:
    description: Apply to join as a member
    usage: /apply
    permission: survivalutil.apply
  heal:
    description: Restore health and hunger of a player
    usage: /heal <player>
    permission: survivalutil.heal
  help:
    description: Displays help menu
    usage: /help
    permission: survivalutil.help
  unaccept:
      description: Undo accept of a member
      usage: /unaccept <player>
      permission: survivalutil.unaccept